### PR TITLE
Retired course message

### PR DESCRIPTION
**Pull request by jgagne**
## What this PR does

- Adds an interim message banner to a soon-to-be retired course (sorry, GYM-100) via CSS

### Preview

Once on staging…

#### Catalog

- https://courses.gymna.si/courses

gym-retired-course-catalog

#### About

- https://courses.gymna.si/courses/GYM/100/0/about

gym-retired-course-about

#### Info

- https://courses.gymna.si/courses/GYM/100/0/info

gym-retired-course-info

#### Courseware

- https://courses.gymna.si/courses/GYM/100/0/courseware

gym-retired-courseware

### CODE REVIEW

**Review by rediris — APPROVED** [review]
Works for me!

My vote: get this on staging so that we can see it in the wild, and then we can make any additional alterations if necessary.

**Comment by andrewpmiller** [comment]
@jgagne — I don't think that the part about enrollment closing is needed on these pages... since they would have already enrolled at the point where they'd see them:
- the syllabus page (courses.gymna.si/courses/GYM/100/0/info)
- the lessons (courses.gymna.si/courses/GYM/100/0/courseware)

If anything, we could point out that they need to complete the course by 3/25... (seemingly obvious but worth stating)

**Comment by jgagne** [comment]
@andrewpmiller and @keircullenjaney thoughts on this update for those pages? ↑

> This course is retiring and all coursework needs be completed by March 25, 2022.

**Comment by andrewpmiller** [comment]
@jgagne your remix for the post-enroll pages is 🎯

**Review by andrewpmiller — APPROVED** [review]

**Review by keircullenjaney — APPROVED** [review]

**Pull request merged**
