### PR TITLE
Gym brand pride flag variant

### PR DESCRIPTION
**Pull request by jgagne**
## What this PR does

- Updates site brand
- Updates site OG image
- Optimizes Open edX logo

### CODE REVIEW

**Comment by rediris** [comment]
@jgagne I think there's a weird error with the SVG:

When attempting to view the raw file at https://raw.githubusercontent.com/gymnasium/gymcms/f3c7d61ee584ef446c7570bc737a75972fc6103d/img/brand/svg/gymnasium-logo-white.svg I got this error:
```
This page contains the following errors:
error on line 11 at column 59: Namespace prefix xlink for href on use is not defined
Below is a rendering of the page up to the first error.
```

In taking a brief look at the source of the SVG, I'm not sure what the issue is, but it almost looks to me like maybe there's a missing closing `</g>` tag.

**Review by rediris — CHANGES_REQUESTED** [review]
See notes about SVG file.

**Comment by rediris** [comment]
It looks like the `<g fill="none">` doesn't have a closing tag?

**Review by jgagne — COMMENTED** [review]
Thanks for that catch, SVG is updated.

**Comment by rediris** [comment]
Hey @jgagne thanks for making the update. Unfortunately, it didn't fix the issue. I can't actually view the SVG properly at all.
I did a little research, and this might be the answer: https://stackoverflow.com/a/59138201

**Review by andrewpmiller — CHANGES_REQUESTED** [review]
`gymnasium-logo-white.svg` is still throwing errors (different but still errors)

**Comment by jgagne** [comment]
@rediris Thanks, I'll address this issue.

**Review by jgagne — COMMENTED** [review]
Thanks for flagging this, SVG should now render as a standalone graphic.

**Review by rediris — APPROVED** [review]
Looks good! Thank you!

**Review by rediris — APPROVED** [review]

**Review by andrewpmiller — APPROVED** [review]

**Pull request merged**
