### PR TITLE
Update Privacy Policy

### PR DESCRIPTION
**Pull request by mbifulco**
Updating the content of our privacy policy based on the new one.

### CODE REVIEW

**Comment by mbifulco** [comment]
This will fix https://github.com/gymnasium/tracker/issues/9

**Comment by mbifulco** [comment]
Content preview is [here](https://deploy-preview-304--thegymcms.netlify.com/static/privacy-policy/) 👍

**Comment by jgagne** [comment]
@mbifulco I'm also working on an update for this page.

**Comment by mbifulco** [comment]
Ah, okay! I'll close this.  Thanks Justin 🙏

**Pull request closed without merging**
