### PR TITLE
Update links on the jobs page

### PR DESCRIPTION
**Pull request by andrewpmiller**
## What this PR does:

- moves job links content to markdown
- updates links (resolves gymnasium/tracker#8)

### CODE REVIEW

**Review by jgagne — APPROVED** [review]
A lot of great links, without any rot.

**Comment by jgagne** [comment]
@andrewpmiller @keir did we want to wait and include the latest, soon to be published, blog post before merging?

**Comment by andrewpmiller** [comment]
@jgagne - since this fixes a lot of currently broken links, I’d rather get this merged sooner (still needs a release to production) to address the bugs. We can update when the blog article is published.

**Comment by jgagne** [comment]
@andrewpmiller sounds good.

**Pull request merged**
