### PR TITLE
Update privacy policy

### PR DESCRIPTION
**Pull request by jgagne**
This PR does:

- Updates content with latest privacy policy
- Adds internal navigation
- Adds section structure, semantics, and styles
- Fixes gymnasium/tracker#9

### CODE REVIEW

**Comment by mbifulco** [comment]
Any idea why this didn't deploy @andrewpmiller?

**Comment by andrewpmiller** [comment]
@mbifulco maybe because there was a commit made shortly after the PR was opened... maybe it caused the build/deploy to stop?

**Comment by andrewpmiller** [comment]
**Deploy preview:** https://deploy-preview-305--thegymcms.netlify.com/static/privacy-policy/

**Review by andrewpmiller — APPROVED** [review]
Approved for staging (so we can see it styled etc)

**Comment by mbifulco** [comment]
Looks good on staging! 👍

**Pull request merged**
