### PR TITLE
[Release]: Portfolio Take 5s and Jobs feed update

### PR DESCRIPTION
**Pull request by jgagne**
- Portfolio Take 5s 
  - Hero: https://courses.gymna.si
  - Catalog: https://courses.gymna.si/courses/take5 and https://courses.gymna.si/courses/take5#career-skills
- Jobs: https://courses.gymna.si/jobs#jobs

gym-take5-hero-update

### CODE REVIEW

**Review by andrewpmiller — APPROVED** [review]
LOVE IT!

**Comment by andrewpmiller** [comment]
And @jgagne - the notes and links in your PRs are exemplary. Always. 🙏

**Review by rediris — APPROVED** [review]

**Comment by jgagne** [comment]
The CTA button style differs on my local build (above) to staging (below). Let me know preference.

image

**Comment by andrewpmiller** [comment]
@jgagne - the one link I didn't check 🤣
I think it _should_ be blue...

**Comment by jgagne** [comment]
Working on more blue! 😂

**Pull request merged**
