### PR TITLE
Update remote work content

### PR DESCRIPTION
**Pull request by jgagne**
## What this PR does:

Updates Remote Work resources page meta URL to match meta URL on https://thegymnasium.com/remote-work, OG description, and adds a link to the global footer.

**Meta URL**

`<div hidden="">error loading https://thegymcms.com/static//hub-pages/meta/remote-work-meta</div>`

### CODE REVIEW

**Comment by jgagne** [comment]
@mbifulco Please have a look-see if the update to the meta URL is correct. Also I noticed double forward slacks in the URL `https://thegymcms.com/static//` in the loading error:

`<div hidden="">error loading https://thegymcms.com/static//hub-pages/meta/remote-work-meta</div>`

**Comment by mbifulco** [comment]
Hm - what URL should I be loading? https://staging.thegymcms.com/static/hub-pages/meta/remote-work-meta returns a 404

**Comment by jgagne** [comment]
Yup, the update in https://github.com/gymnasium/gymcms/pull/401/commits/51f3f9d4b4a1438684908672f2698e7ad69498a5 should update the meta URL to match https://staging.thegymcms.com/static/hub-pages/meta/remote-work-meta to avoid the 404. Should the end forward slash be removed in `/static/hub-pages/meta/remote-work-meta/`?

**Comment by mbifulco** [comment]
Oh! I missed that this was a PR - I thought it was an issue.  Perfect.  Thanks!

**Review by mbifulco — APPROVED** [review]

**Pull request merged**
