### PR TITLE
[Feature]: page speed improvements

### PR DESCRIPTION
**Pull request by rediris**
What this PR does:
1. combines all meta layouts into one: `meta` layout (`One Meta to Rule Them All`) ⚔️ 
2. moves theme JS to gymnasium.js
3. improves JSON fallback behavior for the jobs module
4. creates meta blocks for generic pages
5. moves most partial theme components to `/partials/` folder
6. reduces the number of requests made from the theme by moving JS includes to the footer, and CSS to the meta
7. reduces number of gymcms requests from the theme
8. Adds global inline CSS to bottom of  the meta include (this is inline CSS that was formerly served up by the system status component)
9. updates redirects accordingly
10. customizes account deletion text in the dashboard
11. one less gymcms include by moving system status to a footer include (JS driven)

This PR is directly related to: https://github.com/gymnasium/openedx-theme/pull/84

## Testing Procedures
Test catalog meta:
* https://deploy-preview-650--thegymcms.netlify.app/tests/catalog/metas

Test webinar meta:
* https://deploy-preview-650--thegymcms.netlify.app/tests/webinars/metas

### Manual Meta Testing
Per-environment meta comparison (a bit cumbersome, because you have to view source per page):
* https://deploy-preview-650--thegymcms.netlify.app/tests/meta/env-comparison

Probably the most expedient manual test is to check the source of one of each type of course & webinar on the current PR branch and compare to the production version:
#### GYM-100
* https://deploy-preview-650--thegymcms.netlify.app/courses/full/gym-100/meta/
* https://thegymcms.com/courses/full/gym-100/meta/

#### GYM-001
* https://deploy-preview-650--thegymcms.netlify.app/courses/gym-shorts/gym-001/meta/
* https://thegymcms.com/courses/gym-shorts/gym-001/meta/

#### GYM-5001
* https://deploy-preview-650--thegymcms.netlify.app/courses/take5/gym-5001/meta/
* https://thegymcms.com/courses/take5/gym-5001/meta/

#### Webinar:
* https://deploy-preview-650--thegymcms.netlify.app/webinars/decade-of-responsive-web-design/meta/
* https://thegymcms.com/webinars/decade-of-responsive-web-design/meta/

Lastly, manually check the links in the ["Everything Else" section](https://deploy-preview-650--thegymcms.netlify.app/tests/meta/env-comparison#everything-else), with the understanding that staging & production versions do not currently exist for About, Support, FAQ, Dashboard, Home and Privacy Policy.

### CODE REVIEW

**Comment by jgagne** [comment]
@rediris — Hell yeah! Beyond words!

A few links to double-check (duplicated results for thoroughness):

**Manual Meta Testing** 
- https://deploy-preview-650--thegymcms.netlify.app/tests/meta/env-comparison

Code | Occurrences | What to do
-- | -- | --
404 | 14 | The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link.
500 | 1 | This is a server side problem. Check the URI.

See https://validator.w3.org/checklink?uri=https%3A%2F%2Fdeploy-preview-650--thegymcms.netlify.app%2Ftests%2Fmeta%2Fenv-comparison&hide_type=all&depth=&check=Check

**Everything Else** 
- https://deploy-preview-650--thegymcms.netlify.app/tests/meta/env-comparison#everything-else

Code | Occurrences | What to do
-- | -- | --
404 | 14 | The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link.

See https://validator.w3.org/checklink?uri=https%3A%2F%2Fdeploy-preview-650--thegymcms.netlify.app%2Ftests%2Fmeta%2Fenv-comparison%23everything-else&hide_type=all&depth=&check=Check

**Comment by rediris** [comment]
@jgagne that's a great tool to check our broken links!

In this case, I believe all 14 broken link results are as expected.

The new meta includes for the following six pages don't exist on staging or production: About, FAQ, Support, Dashboard, Privacy Policy, Home (this accounts for 12 of the broken links)

The course meta for GYM-019 had the incorrect URL set on staging and production, and this accounts for the remaining 2 broken links).

```
error Line: 1102 https://staging.thegymcms.com/privacy-policy/meta/
Status: 404 Not Found
The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link.

error Line: 1072 https://staging.thegymcms.com/faq/meta/
Status: 404 Not Found
The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link.

error Line: 1005 https://thegymcms.com/about/meta/
Status: 404 Not Found
The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link.

error Line: 1085 https://thegymcms.com/home/meta/
Status: 404 Not Found
The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link.

error Line: 1075 https://thegymcms.com/faq/meta/
Status: 404 Not Found
The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link.

error Line: 1042 https://staging.thegymcms.com/dashboard/meta/
Status: 404 Not Found
The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link.

error Line: 1132 https://staging.thegymcms.com/support/meta/
Status: 404 Not Found
The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link.

error Line: 1002 https://staging.thegymcms.com/about/meta/
Status: 404 Not Found
The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link.

error Line: 1135 https://thegymcms.com/support/meta/
Status: 404 Not Found
The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link.

error Line: 1082 https://staging.thegymcms.com/home/meta/
Status: 404 Not Found
The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link.

error Line: 286 https://thegymcms.com/courses/gym-shorts/gym-019/meta/
Status: 404 Not Found
The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link.

error Line: 283 https://staging.thegymcms.com/courses/gym-shorts/gym-019/meta/
Status: 404 Not Found
The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link.

error Line: 1105 https://thegymcms.com/privacy-policy/meta/
Status: 404 Not Found
The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link.

error Line: 1045 https://thegymcms.com/dashboard/meta/
Status: 404 Not Found
The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link.
```

**Comment by rediris** [comment]
And I suspect the 500 error was a temporary glitch - it didn't happen to me when I tried running the test.

**Comment by jgagne** [comment]
@jgagne - Phew, very cool!

🚀 And speedy updates!!!

`/courses/` for example:

- **Deploy Preview**: https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fdeploy-preview-650--thegymcms.netlify.app%2Fcourses%2F
- **Staging**: https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fstaging.thegymcms.com%2Fcourses%2F
- **Production**: https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fthegymnasium.com%2Fcourses%2F

**Comment by rediris** [comment]
@jgagne could we do one for https://courses.gymna.si/courses ?

**Comment by jgagne** [comment]
**Update**:

`https://courses.gymna.si/courses` 
- https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fcourses.gymna.si%2Fcourses

**Comment by rediris** [comment]
Looks like these updates actually do very little to improve pagespeed on the gymnasium theme hosts!

I did notice a difference between the mobile vs desktop pagespeed tests (you can click on the Mobile tab once the results show):

Desktop Staging:
* https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fcourses.gymna.si%2F&tab=desktop

Desktop Production:
* https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fthegymnasium.com%2F&tab=desktop

**Comment by jgagne** [comment]
A little is a lot (incrementally)!

**Review by jgagne — DISMISSED** [review]
Merge when ready.

**Pull request merged**
