### PR TITLE
Update GYM-100 short description

### PR DESCRIPTION
**Pull request by jgagne**
## What this PR does

- Adds inline retired message to meta/short description

### CODE REVIEW

**Review by rediris — DISMISSED** [review]

**Comment by rediris** [comment]
Are you going to add the updated image too?

**Comment by jgagne** [comment]
@rediris From the discussion it seemed that an update to the text description was the way to go, rather than to the image.

**Comment by rediris** [comment]
> @rediris From the discussion it seemed that an update to the text description was the way to go, rather than to the image.

OK, right!

**Comment by jgagne** [comment]
@rediris Alternatively, sans text alteration to the image: (Perhaps a more subtle visual indication of retirement?)

gym-100-social

**Comment by andrewpmiller** [comment]
The grayscale treatment is a differentiator only as long as we continue to use the colors though. If anything, this sample makes me like the monotone take on the artwork even more! 😉

**Comment by rediris** [comment]
Agreed about the monochromatic treatment. My vote: roll it out, as we'll have to revamp all the artwork in the future anyway, once we roll out design changes...

**Comment by rediris** [comment]
Alternately, add a giant "RETIRED" stamp across the entire graphic, diagonally oriented.

**Comment by jgagne** [comment]
@andrewpmiller and @rediris for the courseware as well? (At least for now…) We can shelve it for later, too, and rely on the text in the description, as it is an edge case.

gym-100-retired-dashboard

**Comment by rediris** [comment]
I'm working on the redirect for the courseware on dev - running into some issues, but are you referring to the meta? I think that the meta for the course should get updated automatically for all of the subpages in the course experience...

Does that answer your question? Let me know if I got confused...

**Comment by jgagne** [comment]
> I'm working on the redirect for the courseware on dev - running into some issues, but are you referring to the meta? I think that the meta for the course should get updated automatically for all of the subpages in the course experience...
> 
> Does that answer your question? Let me know if I got confused...

I'd update the course artwork that was uploaded via Studio for the course about page and dashboard to get the grayscale treatment.

**Review by rediris — APPROVED** [review]

**Review by andrewpmiller — COMMENTED** [review]
Needless to say — I'm good with this one... whenever it's to be merged...

**Review by andrewpmiller — APPROVED** [review]

**Review by rediris — APPROVED** [review]
We should roll this out ASAP, right?

**Pull request merged**
