### PR TITLE
hero refresh

### PR DESCRIPTION
**Pull request by andrewpmiller**

### CODE REVIEW

**Comment by jgagne** [comment]
Hero update [looks good](https://deploy-preview-98--gymcms.netlify.com/tests/hero.html), but I'm unclear on what conflict needs to be resolved in `home/hero.html`.

**Comment by mbifulco** [comment]
I'll take care of that conflict 👍

**Comment by mbifulco** [comment]
Should be good to go! 🎉

**Review by jgagne — APPROVED** [review]
Ship it!

**Pull request merged**
