### PR TITLE
[Feature]: Stage I Performance Improvements

### PR DESCRIPTION
**Pull request by rediris**
Original PR for reference: https://github.com/gymnasium/gymcms/pull/796

## What this PR Does:
- (in general, this PR is an early stage in the the process of streamlining browser requests in order to reduce loading time)
- improved meta tags for preload/prefetch
- some open edx JS files have been added to the `_includes/js/vendors/` directory. For the most part, these files can safely be ignored for this PR, as they are not doing anything yet.
- combine job module CSS and JS with main CSS/JS files
- combine some of our JS files (see `js/main.js` (the cookiebanner.js being an exception, and there are reasons for this).

### CODE REVIEW

**Review by jgagne — APPROVED** [review]
That's a lot of Java! 😜 Looks good!

**Review by andrewpmiller — COMMENTED** [review]
Review a draft PR? 🤷‍♂️

**Comment by rediris** [comment]
> Review a draft PR? 🤷‍♂️

Oops, somehow I forgot to make it official!

**Comment by rediris** [comment]
big brother eye

**Pull request merged**
