### PR TITLE
Update collections content and landing page

### PR DESCRIPTION
**Pull request by jgagne**
## What this PR does:

- Updates Remote Work collection salary-related content; fixes broken image after Jobs page update
  - See broken image and outdated salary content: https://courses.gymna.si/remote-work
- Updates Remove Work Criticism and Feedback section layout 
- Updates Jobs indentation
- Adds exclude logic to landing page; excludes Design Systems collection (for now)
  - See exclude: https://deploy-preview-588--thegymcms.netlify.app/static/collections/
- Updates Collections landing page specific short descriptions

---
Link to test the remote work collection page (top and bottom includes only):
https://deploy-preview-588--thegymcms.netlify.app/tests/collections/remote-work/

### CODE REVIEW

**Review by andrewpmiller — CHANGES_REQUESTED** [review]
@jgagne There's an issue with the Criticism and Feedback links

image

**Review by jgagne — COMMENTED** [review]
Added secure URL for How to Crit

**Comment by andrewpmiller** [comment]
@jgagne It was actually the two links per line in that section that I thought was an error 🤣

**Review by jgagne — COMMENTED** [review]
@andrewpmiller — No prob. Layout updated.

**Comment by jgagne** [comment]
@andrewpmiller — Right. Happy to review use of a single description for both to avoid duplicate short description entries based on context.

**Review by andrewpmiller — APPROVED** [review]
👍

**Pull request merged**
