### PR TITLE
Update GYM-5040 transcript

### PR DESCRIPTION
**Pull request by jgagne**
## What this PR does:

- Updates GYM-5040 transcript content
  - Updates definition/keyword style
  - Updates code example and screen reader order
- Updates Take 5 top test include
  - Updates Prism JS as served on staging/production via CDN
  - Adds inline script for language specific data-language attribute and label

**Current Prism JS rendering on staging/production Take 5 transcripts**

gym-transcript-prism-no-code-language

**Current Prims JS rendering on local dev Take 5 transcripts**

gym-transcript-prism-code-language

### CODE REVIEW

**Comment by jgagne** [comment]
@mbifulco I did a bit more digging into Prism JS differences and captured my findings https://github.com/gymnasium/gymcms/pull/496/commits/1d2d6695987018811e141e7ad2898b2571572bc2 (at least the version of Prism JS that I was using for local dev).

**Comment by mbifulco** [comment]
Good find Justin - I'll see about updating the version of Prism we use for exams on our next release, too

**Comment by jgagne** [comment]
Cool, Mike. My inline script may be a bit hacky, but I thought I'd give it a go, at least something we can test or revise.

**Comment by mbifulco** [comment]
Hm, it looks like that _doesn't_ actually work in situ on staging - I'll see about updating the theme appropriately.

**Pull request merged**
