### PR TITLE
[release] Webinars + take 5

### PR DESCRIPTION
**Pull request by mbifulco**

### CODE REVIEW

**Review by jgagne — COMMENTED** [review]
Pardon for all the bad link updates on the collection pages.

One possible 404 found: https://thegymnasium.com/webinars/state-of-responsive-design

**Comment by mbifulco** [comment]
For whatever reason, I had [https://thegymnasium.com/webinars/state-of-responsive-web-design](https://thegymnasium.com/webinars/state-of-responsive-web-design) as the URL- which does work.  Can you update the CMS links to match that?

**Comment by jgagne** [comment]
#357 should take care of the URL mismatch.

**Comment by jgagne** [comment]
Missed the meta. Update: #358

**Review by andrewpmiller — APPROVED** [review]
Looks good to me...

**Review by jgagne — CHANGES_REQUESTED** [review]
Everything looks good, except for the RWD webinar landing page (https://courses.gymna.si/webinars/state-of-responsive-web-design) which still isn't loading as intended.

**Review by jgagne — APPROVED** [review]

**Pull request merged**
