### PR TITLE
Remote work hub page

### PR DESCRIPTION
**Pull request by jgagne**
## What this PR does:

Adds remote work resources hub page content.

### Preview

(Without images [currently not on staging].)

https://deploy-preview-390--thegymcms.netlify.app/tests/remote-work/

### Screenshot

(Without Remote Jobs module include.)

remote-work-resources-hub-page

### CODE REVIEW

**Review by andrewpmiller — COMMENTED** [review]
@jgagne this looks fanastic! One question I have is about the inclusion of the remote jobs (at other sites). I think Jeremy called that out as problematic, so I think we'd considered omitting it. Did you intend to swap that out with the actual jobs module when it's available?

**Comment by jgagne** [comment]
@andrewpmiller thank-you! Cool, I'll update the page, screenshot, and the Google doc with the omission (as well as inclusions that developed along the way). I'd later like to reuse a version of the header language for the Remote Jobs module include and revisit, if any static markup is needed to be left in place, after syncing with @mbifulco on any implementation adjustments.

**Review by andrewpmiller — APPROVED** [review]
@jgagne this is tremendous! Style-wise I'm thinking that the jobs page might benefit from this bolder treatment... if the hierarchy justifies it. I'll approve/squash/merge so we can get this live on staging... and we can tweak as needed when @mbifulco is ready with the de-header-ized job module.

**Comment by andrewpmiller** [comment]
😲
image

**Comment by jgagne** [comment]
@andrewpmiller all systems go on giving the jobs page a facelift. I'll continue to forge ahead, now that I have @jeremyosborn's walking playlist to keep the momentum. 🎧

**Pull request merged**
