### PR TITLE
[release] Updating footer css to unbug a bug

### PR DESCRIPTION
**Pull request by mbifulco**
@jgagne @andrewpmiller I just want to make sure the other commits that found their way onto staging are ok in production before merging this.  If not, I'll create a separate branch to hotfix production from. Just let me know!

### CODE REVIEW

**Review by jgagne — APPROVED** [review]
Is it possible to sneak #122  into this PR? Otherwise, all looks good.

**Comment by mbifulco** [comment]
Yep! Incoming.

**Comment by mbifulco** [comment]
@jgagne can you take a look at this again? [staging](https://courses.gymna.si/) has this code deployed on it, but the sign up button still seems inaccessible.  It seems like it's being blocked by this element:

image


It becomes clickable again if I remove the `content` from the `::before` bit on the CSS rule. This is in Chrome Desktop view on MacOS.

**Comment by jgagne** [comment]
@mbifulco #123 should squash this bug.

**Comment by mbifulco** [comment]
Thank you!

**Pull request merged**
