### PR TITLE
Update Take 5 hero CSS animation

### PR DESCRIPTION
**Pull request by jgagne**
# What this PR does

- Updates CSS animation; adds @include fades keyframe override
- Updates decimal value, adds leading zero for consistency/readability

### CODE REVIEW

**Comment by jgagne** [comment]
@rediris — If you have time to tinker, please incorporate my [keyframe override](https://github.com/gymnasium/gymcms/blob/a9f9c54f1b0b4af1a5990c0219128aa9198c4eb2/css/hero-take5-campaign.scss#L91-L117) into [`_sass/_animations.scss`](https://github.com/gymnasium/gymcms/blob/a75e453f9277d3f652a35dd390b21378e5afc4bd/_sass/_animations.scss#L303-L331), else we can ship as is.

**Comment by rediris** [comment]
@jgagne I'll take a quick peek.

**Comment by rediris** [comment]
@jgagne all set - I ditched the convoluted for loops and just used plain CSS. Let me know if this makes sense, or hit me up with any questions.

**Comment by jgagne** [comment]
@rediris — Perfect!

**Review by rediris — APPROVED** [review]
Let's get this out the door!

**Pull request merged**
