### PR TITLE
[Feature]: adds sitemap.xml

### PR DESCRIPTION
**Pull request by rediris**
Sitemap XML:
* https://deploy-preview-607--thegymcms.netlify.app/sitemap.xml

Updates featured-courses.json:
* https://deploy-preview-607--thegymcms.netlify.app/feeds/featured-courses.json

Deprecated `baseurl` in use, since we are now serving the site from the root instead of the `static` folder. See https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/ for details...

---
Post merge: for ease of testing once this is on staging, we can check all of our generated pages/page URLs: https://deploy-preview-607--thegymcms.netlify.app/sitemap (or https://staging--gymcms.netlify.com/sitemap)

### CODE REVIEW

**Review by andrewpmiller — COMMENTED** [review]
404: https://thegymnasium.com/webinars/state-of-responsive-design
Should be: https://thegymnasium.com/webinars/state-of-responsive-web-design

There was a twist to this one...

**Comment by rediris** [comment]
> 404: https://thegymnasium.com/webinars/state-of-responsive-design
> Should be: https://thegymnasium.com/webinars/state-of-responsive-web-design
> 
> There was a twist to this one...

@andrewpmiller,

Right-o. I'll update the permalink, in that case.

See here for how the paths will be mapped mapped for this release in the openedx platform: https://github.com/gymnasium/edx-env/blob/open-release/hawthorn.master/lms.env.json#L326-L428

These are copy/pasta'd to Amir and he updates them on each environment's platform manually... unfortunately there is no streamlined commit-based system to update these.

**Comment by rediris** [comment]
> > 404: https://thegymnasium.com/webinars/state-of-responsive-design
> > Should be: https://thegymnasium.com/webinars/state-of-responsive-web-design
> > There was a twist to this one...
> 
> @andrewpmiller,
> 
> Right-o. I'll update the permalink, in that case.
> 
> See here for how the paths will be mapped mapped for this release in the openedx platform: https://github.com/gymnasium/edx-env/blob/open-release/hawthorn.master/lms.env.json#L326-L428
> 
> These are copy/pasta'd to Amir and he updates them on each environment's platform manually... unfortunately there is no streamlined commit-based system to update these.

Not sure why web0005 needed to be an exception on development, but I'm stripping the logic for this, unless there's a wholesome reason for keeping it.

**Review by andrewpmiller — DISMISSED** [review]
@rediris I haven't done any comprehensive tests to validate that there aren't any unintended consequences to doing away with `baseurl` — and I have a nagging suspicion that I've constructed paths in some of these pages that have assumed the `/` 🤷 

I'm good with merging so we can test it all on staging

**Comment by rediris** [comment]
> @rediris I haven't done any comprehensive tests to validate that there aren't any unintended consequences to doing away with `baseurl` — and I have a nagging suspicion that I've constructed paths in some of these pages that have assumed the `/` 🤷
> 
> I'm good with merging so we can test it all on staging

Sounds good. I think it will be fine - every instance of `baseurl` that was referenced was followed by a hard-coded path. Which kind of confused me, because the production yml had the slash but the other environments didn't. Either way, more to come.

**Pull request merged**
