### PR TITLE
[Feature]: Recreate 2021/2020 cards with HTML/CSS

### PR DESCRIPTION
**Pull request by rediris**
## What this PR does:
- adds HTML/CSS based recreation of the 2020n & 2021 holiday cards

## Extra
- streamlines localhost behavior for CSS files (essentially moves references to CSS files out of the content to the head via liquid tags)

## Preview (screencap)
Screen Shot 2022-12-16 at 4 04 51 PM
Screen Shot 2022-12-16 at 3 12 56 PM

### CODE REVIEW

**Review by jgagne — CHANGES_REQUESTED** [review]
Very cool styling! Also, including the CSS in the front matter is hot! One minor layout change would be to give the code in the card more spacing from the left (and right). Maybe double it to let it breathe a bit more. Otherwise, ship it!

**Comment by rediris** [comment]
> Very cool styling! Also, including the CSS in the front matter is hot! One minor layout change would be to give the code in the card more spacing from the left (and right). Maybe double it to let it breathe a bit more. Otherwise, ship it!

@jgagne Done! Thanks for the suggestions!

**Comment by jgagne** [comment]
One more minor update: For the 2020 card, size the text all the same size as the element and attribute `<img src=` to better match the printed version.

**Review by jgagne — CHANGES_REQUESTED** [review]
One more minor update: For the 2020 card, size the text all the same size as the element and attribute `<img src=` to better match the printed version.

**Comment by rediris** [comment]
> One more minor update: For the 2020 card, size the text all the same size as the element and attribute `<img src=` to better match the printed version.

Good catch. Turns out you need to wrap every single thing in those span tags for it to work properly. It should all be monospaced now.

**Review by jgagne — APPROVED** [review]
Very taste!

**Pull request merged**
